doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AppUser:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/User/Entity'
                prefix: 'App\User\Entity'
                alias: App\User
            AppBooking:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Booking/Infrastructure/Entity'
                prefix: 'App\Booking\Infrastructure\Entity'
                alias: App\Booking
            AppClient:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Client/Entity'
                prefix: 'App\Client\Entity'
                alias: App\Client
            AppRoom:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Room/Entity'
                prefix: 'App\Room\Entity'
                alias: App\Room
            AppInvoice:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Invoice/Entity'
                prefix: 'App\Invoice\Entity'
                alias: App\Invoice
